apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sigilo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sigilo
  template:
    metadata:
      labels:
        app: sigilo
    spec:
      containers:
        - name: sigilo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
