apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sigilo-service
spec:
  selector:
    app: sigilo
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
